[package]
name = "hive"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.0"
apis = { path = "../apis", features = ["bevy"]}
bevy_pancam = "0.12.0"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
